# # POST http://localhost:3000/build-travel-plan
# Content-Type: application/json

# {
#     "travelTo": "Provo, UT", 
#     "travelFrom": "South Korea", 
#     "travelWith": "Car", 
#     "fromDate": "May 6", 
#     "toDate": "May 9", 
#     "specificActivity": "school tour, museum, hiking, shopping, eating, etc."
# }

# POST https://places.googleapis.com/v1/places:searchText?fields=* HTTP/1.1
# Content-Type: application/json
# X-Goog-Api-Key: AIzaSyDqfOcm6kCq9yVXAuAqHJEBNwOi7iZOvs8
# X-Goog-FieldMask: *

# {
#     "textQuery": "Spicy Vegetarian Food in Sydney, Australia"
# }


# POST http://localhost:3000/build-travel-plan
# Content-Type: application/json

# {
#     "travelTo": "Provo, UT", 
#     "travelFrom": "South Korea", 
#     "travelWith": "Car", 
#     "fromDate": "May 6", 
#     "toDate": "May 9", 
#     "specificActivity": "school tour, museum, hiking, shopping, eating, etc."
# }
# POST http://localhost:3000/place-reviews
# Content-Type: application/json

# {
#     "textQuery": "Spicy Vegetarian Food in Sydney, Australia"
# }
# POST http://localhost:3000/place-reviews
# Content-Type: application/json

# {
#     "textQuery": "Spicy Vegetarian Food in Sydney, Australia"
# }

# GET http://localhost:3000/searchHotels
# Content-Type: application/json

# {
#     "prompt": "london eye",
#     "arrival": "2024-05-05",
#     "departure": "2024-05-08"
# }

# GET http://localhost:3000/getOneWayTrip
# Content-Type: application/json

# {
#     "fromCity": "london",
#     "toCity": "seoul",
#     "departDate": "2024-05-08"
# }

# POST http://localhost:3000/build-travel-plan

# Content-Type: application/json

# {
#     "travelTo": "Provo, UT", 
#     "travelFrom": "South Korea", 
#     "travelWith": "Car", 
#     "fromDate": "May 6", 
#     "toDate": "May 9", 
#     "specificActivity": "school tour, museum, hiking, shopping, eating, etc."
# }

# GET http://localhost:3000/searchHotels
# Content-Type: application/json

# {
#     "prompt": "london eye",
#     "arrival": "2024-05-05",
#     "departure": "2024-05-08
# }
GET http://localhost:3000/getLocationPhotos
Content-Type: application/json

{
    "prompt": "seoul"
}


GET http://localhost:3000/searchHotels
Content-Type: application/json

{
    "prompt": "london eye",
    "arrival": "2024-05-02",
    "departure": "2024-05-05"
}


GET http://localhost:3000/searchHotels
Content-Type: application/json

{
      "prompt": "seoul"
}